apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: default
spec:
  type: NodePort  # Você pode usar ClusterIP ou LoadBalancer dependendo do seu ambiente
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
