apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==   # "mongoadmin" encoded in base64
  mongo-root-password: cGFzc3dvcmQ=        # "password" encoded in base64
