apiVersion: v1
kind: Service
metadata:
  name: pagamentos-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: pagamentos-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
