name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust 1.75
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.75.0

    - name: Install Clippy
      run: rustup component add clippy

    - name: Run Clippy
      env:
        CARGO_TERM_COLOR: always
      run: cargo clippy

    - name: Install Sonar Scanner
      run: |
        curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli.zip -d $HOME
        export PATH="$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH"

    - name: Run SonarCloud Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        SONAR_ORG: ${{ secrets.SONARCLOUD_ORGANIZATION }}
      run: sonar-scanner \
            -Dsonar.organization=${{ secrets.SONARCLOUD_ORGANIZATION }} \
            -Dsonar.projectKey=postech-5soat-grupo-25 \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }}