name: Rust Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust 1.75
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.75.0

    - name: Install Clippy
      run: rustup component add clippy

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features