name: Rust CI

# Executa o workflow apenas em eventos de Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust 1.75
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.75.0

    - name: Install Clippy
      run: rustup component add clippy

    - name: Run Clippy
      env:
        CARGO_TERM_COLOR: always
      run: |
        # Executa o Clippy e redireciona a saída para um arquivo de log
        cargo clippy > clippy.log 2>&1
        
        # Verifica se há avisos na saída do Clippy
        if grep -q "warning:" clippy.log; then
          echo "Warnings found in Clippy output:"
          cat clippy.log
          echo "Please address these warnings."
          # Continua o job, mas destaca que houve avisos
          exit 0
        fi

    - name: Display Clippy Check
      if: always()
      run: cat clippy.log

    - name: Post Clippy Check
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const log = fs.readFileSync('clippy.log', 'utf8');
          github.rest.issues.createComment({
            ...github.context.repo,
            issue_number: github.context.issue.number,
            body: `### Clippy Code Quality Check\n\n\`\`\`\n${log}\n\`\`\``
          });